apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://sonarsource.github.io/helm-chart-sonarqube/
    chart: sonarqube
    targetRevision: 2026.1.0
    helm:
      values: |
        community:
          enabled: true
        replicaCount: 1
        persistence:
          enabled: false
        postgresql:
          enabled: true
        monitoringPasscode: dev-passcode

  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
